# Base configuration.
command_timeout = 10000
add_newline = true

# Command duration.
[cmd_duration]
min_time = 4
show_milliseconds = false
format = " ğŸ•™ $duration "
style = "bold italic #87A752"

# Directory.
[directory]
truncation_length = 3
style = "bold cyan"

# Hostname.
[hostname]
ssh_only = true
style = "bold yellow"

# Character.
[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ–](bold red) "

# Username.
[username]
show_always = false
style_user = "bold green"
style_root = "bold red"

# Packages.
[package]
disabled = false

# Memory.
[memory_usage]
threshold = 70
format = "using [$ram]($style) "
style = "bold red"

# Background jobs.
[jobs]
format = "[$symbol$jobs]($style) "
symbol = "ğŸ”ƒ "
style = "bold blue"

# Git.
[git_branch]
format = "on [$symbol$branch]($style) "
symbol = "î‚  "
style = "bold green"

[git_status]
conflicted = "âœ–"
ahead = "â†‘"
behind = "â†“"
diverged = "â†•"
stashed = "ğŸ’¼"
modified = "*"
staged = "+"
renamed = "Â»"
deleted = "âœ˜"

# Languages & Tools.
[nodejs]
format = "â¬¢ $version "
style = "bold green"

[rust]
format = "ğŸ¦€ $version "
style = "bold red"

[python]
format = "ğŸ $version "
style = "bold blue"

[go]
format = "ğŸ¹ $version "
style = "bold cyan"

[java]
format = "â˜• $version "
style = "bold purple"

[kubernetes]
format = "â˜¸ï¸ $context "
style = "bold blue"

[docker_context]
format = "ğŸ³ $context "
style = "blue bold"

[c]
format = "âš™ï¸ $version "
style = "bold orange"

[dotnet]
format = "â˜ï¸ $version "
style = "bold blue"

[dart]
format = "ğŸ¯ $version "
style = "bold cyan"

[flutter]
format = "ğŸ¦‹ $version "
style = "bold magenta"
